# Generated by Django 5.1.3 on 2024-11-22 05:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ringtone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letter", models.CharField(max_length=1)),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "ringtone_file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="ringtones/"
                        ),
                        upload_to="",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
